# -*- coding: utf-8 -*-
"""TripWise_AI (4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14d_GOPHaypYztfL43wQdYo2-4SDuxNeQ

**Trip Wise AI**

Travel recomendation using AI

**DATA Loading and First Look**
"""

#imports

!pip install kagglehub[pandas-datasets]

"""**louad dataset 1 - worldwide-travel-cities**"""

import kagglehub
path = kagglehub.dataset_download("furkanima/worldwide-travel-cities-ratings-and-climate")
print("Path to dataset files:", path)

import os
print(os.listdir(path))

import pandas as pd
travel_df = pd.read_csv(
    path + "/Worldwide Travel Cities Dataset (Ratings and Climate).csv"
)

travel_df.head()

print(travel_df.shape)
print(travel_df.columns)

travel_df.info()

#remove unwanted columns

travel_df = travel_df.drop(
    columns=["id", "short_description"]
)

travel_df.head()

#check the travel budget
travel_df["budget_level"].value_counts()

"""**louad dataset 2 - hotels**"""

import kagglehub

hotels_path = kagglehub.dataset_download("raj713335/tbo-hotels-dataset")
print("Path to dataset files:", hotels_path)

import os
print(os.listdir(hotels_path))

hotels_df = pd.read_csv(
    hotels_path + "/hotels.csv",
    encoding="latin1"
)

# cleaning columns that have extra space
hotels_df.columns = hotels_df.columns.str.strip()

hotels_df.head()

"""**louad dataset 3 - airports**

"""

import kagglehub

airports_path = kagglehub.dataset_download("divyanshrai/openflights-airports-database-2017")
print("Path to dataset files:", airports_path)

import os
print(os.listdir(airports_path))

# selecting culumns
airport_cols = [
    "airport_id", "name", "city", "country", "iata", "icao",
    "latitude", "longitude", "altitude", "timezone", "dst",
    "tz_database", "type", "source"
]

airports_df = pd.read_csv(
    airports_path + "/airports.csv",
    header=0,
    names=airport_cols #lowercase
)

airports_df.head()

#check the travel budget
import matplotlib.pyplot as plt
travel_df["budget_level"].value_counts().plot(kind="bar")
plt.show()

# Make sure that the data is global and not just for Guinea
print(airports_df["country"].nunique())
airports_df["country"].value_counts().head(10)

# نحتفظ بالمطارات اللي نوعها airport مانحتاج القطارات
airports_df = airports_df[airports_df["type"] == "airport"]

# نخلي كل مدينةو دولة تظهر مرة وحدة بسس عشان ما يتكرر الدمج
airports_df = airports_df.drop_duplicates(subset=["city", "country"], keep="first")

print(airports_df.shape)
print(airports_df[["city", "country"]].head())

#check the colums name
print(hotels_df.columns.tolist())

#  ربطنا المدن مع الفنادق
matched = travel_df.merge(
    hotels_df,
    left_on=["city", "country"],
    right_on=["cityName", "countyName"],
    how="inner"
)

print("Matched (cities + hotels):", matched.shape)

# نربط النايج مع بيانات المطار على مستوى المدينة والدولة
final_df = matched.merge(
    airports_df,
    left_on=["city", "country"],
    right_on=["city", "country"],
    how="left",
    suffixes=("", "_airport")
)

print("Final (cities, hotels , airports):", final_df.shape)
final_df.head()

#حذفت الاعمدة الي معلوماتها اغلبها null ومو مفيدة
final_df = final_df.drop(columns=["FaxNumber", "PhoneNumber", "PinCode", "HotelWebsiteUrl"])
final_df = final_df.drop(columns=["countyCode"])

# في مدن مالها مطار مطابق ولو حذفتها بخسر اسماء فنادق
#فالافضل اسوي feature يوضح هل المطار قريب ولا لا
final_df["has_airport"] = final_df["iata"].notnull().astype(int)


#impute with value , numreicl with 0,-1 . str with unknown
numeric_airport_cols = ["airport_id", "latitude_airport", "longitude_airport", "altitude"]
final_df[numeric_airport_cols] = final_df[numeric_airport_cols].fillna(-1)

text_airport_cols = ["name", "iata", "icao", "timezone", "dst", "tz_database", "type", "source"]
final_df[text_airport_cols] = final_df[text_airport_cols].fillna("Unknown")

#There is no null value
final_df.isnull().sum()

#impute null value
final_df["Address"] = final_df["Address"].fillna("Not specified")# ماحذفتها لان النل قليل و مرتبطة يصفوف

for col in ["Attractions", "Description", "HotelFacilities", "Map"]:# راح افقد بياتات كثيرة لو حذفتها فعبيتها
    final_df[col] = final_df[col].fillna("Not specified")

# واذا الكلمة موجودة ترجعلنا true وتحولها لرقم 1
#والعكس
final_df["is_short_trip"] = final_df["ideal_durations"].str.contains("Short trip").astype(int)
final_df["is_one_week"] = final_df["ideal_durations"].str.contains("One week").astype(int)

final_df.duplicated().sum()

import re

def get_avg_temp(text):
    numbers = re.findall(r'"avg":([\d.]+)', text) # يدور جوا النص عن كل رقم بعد كلمة "avg": ويرجعهم كقائمة
    numbers = [float(n) for n in numbers] # هنا نحولهم لارقام وبعدها نحسب المتوسط
    return sum(numbers) / len(numbers)

final_df["temp_avg_yearly"] = final_df["avg_temp_monthly"].apply(get_avg_temp)

#راح يسير عندنا عامود واحد فيه متوسط حرارة السنة لكل مدينة
# اذا تبون نقدر بعد نسوي الmin & max

final_df[["is_short_trip", "is_one_week", "temp_avg_yearly"]].head()

final_df["cuisine"].head(10)
#مايحتاج encoding

#check null value
final_df.isnull().sum()

final_df["cuisine"].value_counts()

final_df["budget_level"].unique()

# سوينا encoding للبدجت

budget_map = {
    "Budget": 1,
    "Mid-range": 2,
    "Luxury": 3
}

final_df["budget_level_encoded"] = final_df["budget_level"].map(budget_map)

final_df["region"].unique()

# بنستخدم one hot encoding لان موجودعندنا 7 فئات
region_encoded = pd.get_dummies(final_df["region"], prefix="region")
final_df = pd.concat([final_df, region_encoded], axis=1)

final_df.head()
# انضافت الregion

final_df.info()

#حذفت الاعمددة الي سويت لهم فيتشر
final_df = final_df.drop(columns=["region", "budget_level", "ideal_durations", "avg_temp_monthly"])

final_df["HotelRating"].unique()

# سوينا encoding لتقيم الفنادق

rating_map = {
    "OneStar": 1,
    "TwoStar": 2,
    "ThreeStar": 3,
    "FourStar": 4,
    "FiveStar": 5,
    "All": None #مجهول
}

final_df["HotelRating_encoded"] = final_df["HotelRating"].map(rating_map)

final_df["HotelRating_encoded"].isnull().sum()

# نحفظ إشارة إن التقييم كان مجهول قبل ما نعبيه
final_df["rating_was_unknown"] = final_df["HotelRating_encoded"].isnull().astype(int)

# نعبي الفاضي بالوسيط
final_df["HotelRating_encoded"] = final_df["HotelRating_encoded"].fillna(
    final_df["HotelRating_encoded"].median()
)

final_df["HotelRating_encoded"].isnull().sum()

# الاعمدة الي مفروض تدخل الموديل
feature_cols = [
    "latitude", "longitude", "culture", "adventure", "nature", "beaches",
    "nightlife", "cuisine", "wellness", "urban", "seclusion",
    "has_airport", "is_short_trip", "is_one_week", "temp_avg_yearly",
    "budget_level_encoded", "HotelRating_encoded", "rating_was_unknown",
    "region_africa", "region_asia", "region_europe", "region_middle_east",
    "region_north_america", "region_oceania", "region_south_america"
]

X = final_df[feature_cols]
X.info()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

city_level_df = final_df.groupby("city")[feature_cols].mean().reset_index()

#city_level_df = final_df.groupby("city")[feature_cols].mean().reset_index()
# بعدها تسوين scaling وsimilarity وclustering على city_level_df بدل final_df

"""**Cosine Similarity**"""

import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

user_preferences ={
    "latitude":40, "longitude":10, "culture":5, "adventure":2, "nature":5,
    "beaches":4, "nightlife":1, "cuisine":4, "wellness":3, "urban":2, "seclusion":4,
    "has_airport":1, "is_short_trip":1, "is_one_week":0, "temp_avg_yearly":22, "budget_level_encoded":2,
    "HotelRating_encoded":4, "rating_was_unknown":0, "region_africa":0, "region_asia":0, "region_europe":1,
    "region_middle_east":0, "region_north_america":0, "region_oceania": 0, "region_south_america":0

}
user_df= pd.DataFrame([user_preferences])[feature_cols]
user_scaled= scaler.transform(user_df)

similarities= cosine_similarity(user_scaled, X_scaled)[0]
final_df["similarity_score"]= similarities
top_recommendations= final_df.sort_values("similarity_score", ascending= False).head(10)
top_recommendations[["city", "country", "HotelName", "budget_level_encoded", "similarity_score"]]

"""**K-means**"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
inertia = []
k_range = range(2,11)

for k in k_range:
  km= KMeans(n_clusters= k, random_state= 42, n_init= 10)
  km.fit(X_scaled)
  inertia.append(km.inertia_)


plt.plot(k_range, inertia, marker= 'o')
plt.xlabel("number of sets (k)")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

kmeans= KMeans(n_clusters=5, random_state=42, n_init=10)
final_df["cluster"]= kmeans.fit_predict(X_scaled)
final_df["cluster"].value_counts()
for c in sorted(final_df["cluster"].unique()):
  print(f"\n--- Cluster {c} ---")
  unique_cities = (
      final_df[final_df["cluster"]==c][["city", "country"]].drop_duplicates(subset="city").head(10)
  )
  print(unique_cities)

"""*Insight*

Streamlet
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# pandas
# numpy
# scikit-learn
# matplotlib
# seaborn
# xgboost
# plotly

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# """
# TripWise AI — Premium Streamlit Travel Assistant
# Splash screen (SVG heart-path flight animation) -> Main App (Home / nav pages)
# """
# 
# import time
# import streamlit as st
# 
# st.set_page_config(
#     page_title="TripWise AI",
#     page_icon="✈️",
#     layout="wide",
#     initial_sidebar_state="collapsed",
# )
# 
# # ----------------------------------------------------------------------------
# # GLOBAL CSS
# # ----------------------------------------------------------------------------
# def inject_css():
#     st.markdown(
#         """
#         <style>
#         @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700;800&family=Inter:wght@400;500;600;700&display=swap');
# 
#         :root{
#             --sky:#0EA5E9;
#             --blue:#2563EB;
#             --white:#FFFFFF;
#             --light-gray:#F3F6FA;
#             --text-dark:#0F172A;
#             --text-muted:#64748B;
#             --shadow: 0 20px 60px rgba(37,99,235,0.12);
#         }
# 
#         html, body, [class*="css"]  {
#             font-family: 'Inter', sans-serif;
#         }
#         h1,h2,h3, .tw-display {
#             font-family: 'Outfit', sans-serif;
#         }
# 
#         #MainMenu, footer, header {visibility:hidden;}
#         .block-container{ padding-top:1rem; padding-bottom:2rem; max-width: 1200px;}
#         body{ background: linear-gradient(180deg, #F8FBFF 0%, #EFF5FC 100%); }
# 
#         /* ---------------- SIDEBAR ---------------- */
#         section[data-testid="stSidebar"]{
#             background: linear-gradient(180deg, #0B1220 0%, #111B33 100%);
#             border-right: none;
#         }
#         section[data-testid="stSidebar"] * { color:#E2E8F0 !important; }
#         .tw-navlink{
#             display:flex; align-items:center; gap:.6rem;
#             padding:.65rem 1rem; border-radius:14px; margin-bottom:.35rem;
#             font-weight:500; font-size:0.95rem; cursor:pointer;
#             transition: all .25s ease;
#         }
#         .tw-navlink:hover{ background:rgba(14,165,233,0.18); transform: translateX(3px);}
#         .tw-navlink-active{
#             background: linear-gradient(90deg, var(--sky), var(--blue));
#             color:white !important; box-shadow:0 8px 24px rgba(14,165,233,.35);
#         }
#         .tw-logo{
#             font-family:'Outfit',sans-serif; font-weight:800; font-size:1.4rem;
#             background: linear-gradient(90deg,#38BDF8,#60A5FA);
#             -webkit-background-clip:text; -webkit-text-fill-color:transparent;
#             margin-bottom:1.6rem; display:block;
#         }
# 
#         /* ---------------- BUTTONS ---------------- */
#         .stButton>button{
#             background: linear-gradient(90deg, var(--sky), var(--blue));
#             color:white; border:none; border-radius:999px;
#             padding:0.7rem 1.8rem; font-weight:600; font-size:1rem;
#             box-shadow: 0 10px 30px rgba(37,99,235,.35);
#             transition: all .25s ease;
#         }
#         .stButton>button:hover{ transform: translateY(-2px) scale(1.02); box-shadow:0 14px 36px rgba(37,99,235,.45); }
# 
#         /* ---------------- GLASS CARD ---------------- */
#         .tw-glass{
#             background: rgba(255,255,255,0.65);
#             backdrop-filter: blur(16px);
#             -webkit-backdrop-filter: blur(16px);
#             border: 1px solid rgba(255,255,255,0.6);
#             border-radius: 24px;
#             padding: 1.8rem;
#             box-shadow: var(--shadow);
#             transition: transform .3s ease, box-shadow .3s ease;
#         }
#         .tw-glass:hover{ transform: translateY(-6px); box-shadow: 0 26px 70px rgba(37,99,235,.18); }
# 
#         /* ---------------- HERO ---------------- */
#         .tw-hero{ text-align:center; padding: 3.2rem 1rem 1rem 1rem; }
#         .tw-hero h1{
#             font-size: 3.1rem; font-weight:800; color:var(--text-dark);
#             line-height:1.15; margin-bottom:1rem;
#             animation: fadeUp .9s ease both;
#         }
#         .tw-hero p{
#             font-size:1.15rem; color:var(--text-muted); max-width:680px;
#             margin: 0 auto 2rem auto; line-height:1.6;
#             animation: fadeUp .9s ease .15s both;
#         }
#         .tw-badge{
#             display:inline-block; padding:.4rem 1rem; border-radius:999px;
#             background: rgba(14,165,233,.12); color:var(--blue); font-weight:600;
#             font-size:.85rem; margin-bottom:1.2rem; letter-spacing:.02em;
#             animation: fadeUp .9s ease both;
#         }
# 
#         @keyframes fadeUp{
#             from{opacity:0; transform: translateY(16px);}
#             to{opacity:1; transform: translateY(0);}
#         }
#         @keyframes floaty{
#             0%,100%{ transform: translateY(0px) rotate(0deg);}
#             50%{ transform: translateY(-14px) rotate(2deg);}
#         }
#         .tw-float{ animation: floaty 5s ease-in-out infinite; display:inline-block; }
#         .tw-float-slow{ animation: floaty 7s ease-in-out infinite; display:inline-block; }
# 
#         .tw-illustration-row{ display:flex; justify-content:center; gap:2.2rem; font-size:2.6rem; margin: 1.2rem 0 2.4rem 0; }
# 
#         .tw-section-title{ font-weight:700; font-size:1.6rem; color:var(--text-dark); margin: 2.2rem 0 1rem 0;}
#         .tw-muted{ color:var(--text-muted); }
# 
#         .tw-icon-circle{
#             width:52px; height:52px; border-radius:16px;
#             background: linear-gradient(135deg, var(--sky), var(--blue));
#             display:flex; align-items:center; justify-content:center;
#             font-size:1.4rem; margin-bottom:.8rem; color:white;
#             box-shadow: 0 10px 24px rgba(14,165,233,.3);
#         }
#         </style>
#         """,
#         unsafe_allow_html=True,
#     )
# 
# 
# # ----------------------------------------------------------------------------
# # SPLASH SCREEN
# # ----------------------------------------------------------------------------
# def render_splash():
#     st.markdown(
#         """
#         <style>
#         .tw-splash-wrap{
#             position:fixed; inset:0; z-index:9999;
#             background: radial-gradient(circle at 30% 20%, #BFEFFF 0%, #7FD9F0 45%, #4FC3E0 100%);
#             display:flex; align-items:center; justify-content:center;
#             animation: splashFade 5s ease forwards;
#             overflow:hidden;
#         }
#         @keyframes splashFade{
#             0%{ opacity:0; }
#             8%{ opacity:1; }
#             88%{ opacity:1; }
#             100%{ opacity:0; }
#         }
#         .tw-splash-canvas{
#             position:relative; width:min(90vw,1100px); aspect-ratio:1200/750;
#             animation: mapZoom 5s ease forwards;
#         }
#         @keyframes mapZoom{
#             0%{ transform:scale(1.12); }
#             100%{ transform:scale(1); }
#         }
#         .tw-cloud{
#             position:absolute; opacity:.55; filter:blur(0.5px);
#             animation: cloudDrift linear infinite;
#         }
#         @keyframes cloudDrift{
#             from{ transform: translateX(0); }
#             to{ transform: translateX(60px); }
#         }
#         .tw-plane{
#             position:absolute; top:0; left:0; font-size:2.6rem;
#             offset-path: path("M 120 660 C 230 600 300 520 360 460 C 300 430 250 380 255 310 C 260 220 340 155 430 165 C 490 172 535 210 555 260 C 575 210 620 172 680 165 C 770 155 850 220 855 310 C 860 380 810 430 750 460 C 820 500 900 500 940 430 C 985 355 985 270 940 200 C 1005 165 1060 130 1120 90");
#             offset-rotate: auto;
#             animation: flyMotion 4.6s cubic-bezier(.45,.05,.55,.95) forwards, planeFloat 1.4s ease-in-out infinite;
#         }
#         @keyframes flyMotion{
#             0%{ offset-distance:0%; opacity:0; }
#             5%{ opacity:1; }
#             96%{ offset-distance:100%; opacity:1;}
#             100%{ offset-distance:100%; opacity:0;}
#         }
#         @keyframes planeFloat{
#             0%,100%{ margin-top:0px; }
#             50%{ margin-top:-6px; }
#         }
#         .tw-splash-logo{
#             position:absolute; inset:0; display:flex; align-items:center; justify-content:center;
#             flex-direction:column; opacity:0;
#             animation: logoIn 1.1s ease 4.0s forwards;
#         }
#         @keyframes logoIn{
#             0%{ opacity:0; transform:scale(.88);}
#             100%{ opacity:1; transform:scale(1);}
#         }
#         .tw-splash-logo .tw-splash-title{
#             font-family:'Outfit', sans-serif; font-weight:800; font-size:2.6rem; color:white;
#             text-shadow: 0 8px 30px rgba(0,0,0,.15);
#         }
#         .tw-splash-logo .tw-splash-sub{
#             font-family:'Inter', sans-serif; color:rgba(255,255,255,.9); margin-top:.4rem; font-size:1rem;
#         }
#         </style>
# 
#         <div class="tw-splash-wrap">
#           <div class="tw-splash-canvas">
#             <svg viewBox="0 0 1200 750" width="100%" height="100%" style="position:absolute; inset:0;">
#               <!-- soft world silhouette blobs -->
#               <g fill="#ffffff" opacity="0.28">
#                 <ellipse cx="180" cy="180" rx="150" ry="90"/>
#                 <ellipse cx="420" cy="140" rx="120" ry="70"/>
#                 <ellipse cx="230" cy="420" rx="140" ry="110"/>
#                 <ellipse cx="650" cy="200" rx="180" ry="100"/>
#                 <ellipse cx="780" cy="450" rx="160" ry="120"/>
#                 <ellipse cx="1020" cy="250" rx="150" ry="90"/>
#                 <ellipse cx="980" cy="560" rx="120" ry="80"/>
#               </g>
#               <!-- dotted heart flight path -->
#               <path d="M 120 660 C 230 600 300 520 360 460 C 300 430 250 380 255 310 C 260 220 340 155 430 165 C 490 172 535 210 555 260 C 575 210 620 172 680 165 C 770 155 850 220 855 310 C 860 380 810 430 750 460 C 820 500 900 500 940 430 C 985 355 985 270 940 200 C 1005 165 1060 130 1120 90"
#                     fill="none" stroke="#0F172A" stroke-width="4" stroke-dasharray="2 14" stroke-linecap="round" opacity="0.75"/>
#               <!-- start pin -->
#               <g transform="translate(105,635)">
#                 <path d="M15 0 C24 0 30 7 30 15 C30 26 15 40 15 40 C15 40 0 26 0 15 C0 7 6 0 15 0 Z" fill="#EF4444"/>
#                 <circle cx="15" cy="15" r="7" fill="white"/>
#               </g>
#             </svg>
# 
#             <div class="tw-cloud" style="top:12%; left:8%; font-size:2.2rem; animation-duration:9s;">☁️</div>
#             <div class="tw-cloud" style="top:28%; left:60%; font-size:1.6rem; animation-duration:12s;">☁️</div>
#             <div class="tw-cloud" style="top:65%; left:20%; font-size:1.8rem; animation-duration:10s;">☁️</div>
# 
#             <div class="tw-plane">✈️</div>
# 
#             <div class="tw-splash-logo">
#               <div class="tw-splash-title">✈️ TripWise AI</div>
#               <div class="tw-splash-sub">Plan smarter. Travel further.</div>
#             </div>
#           </div>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
# 
# # ----------------------------------------------------------------------------
# # SIDEBAR NAVIGATION
# # ----------------------------------------------------------------------------
# NAV_ITEMS = [
#     ("Home", "🏠"),
#     ("Plan Trip", "🧳"),
#     ("AI Travel Assistant", "🤖"),
#     ("Destination Explorer", "📍"),
#     ("Budget Planner", "💰"),
#     ("Weather", "🌦️"),
#     ("Saved Trips", "❤️"),
#     ("Settings", "⚙️"),
# ]
# 
# def render_sidebar():
#     with st.sidebar:
#         st.markdown('<span class="tw-logo">✈️ TripWise AI</span>', unsafe_allow_html=True)
#         for label, icon in NAV_ITEMS:
#             active = st.session_state.page == label
#             if st.button(f"{icon}  {label}", key=f"nav_{label}", use_container_width=True):
#                 st.session_state.page = label
#                 st.rerun()
# 
# 
# # ----------------------------------------------------------------------------
# # PAGES
# # ----------------------------------------------------------------------------
# def page_home():
#     st.markdown(
#         """
#         <div class="tw-hero">
#             <span class="tw-badge">✨ AI-Powered Travel Planning</span>
#             <h1>✈️ Plan Smarter with<br/>TripWise AI</h1>
#             <p>Your intelligent travel companion that creates personalized itineraries,
#             predicts travel costs, recommends destinations, and helps you explore the
#             world effortlessly.</p>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#     col = st.columns([1, 1, 1])[1]
#     with col:
#         if st.button("Start Planning →", use_container_width=True):
#             st.session_state.page = "Plan Trip"
#             st.rerun()
# 
#     st.markdown(
#         """
#         <div class="tw-illustration-row">
#             <span class="tw-float">🗺️</span>
#             <span class="tw-float-slow">🧳</span>
#             <span class="tw-float">🏝️</span>
#             <span class="tw-float-slow">🛫</span>
#             <span class="tw-float">🏨</span>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#     st.markdown('<div class="tw-section-title">Everything you need to travel smarter</div>', unsafe_allow_html=True)
#     features = [
#         ("🎯", "Personalized Recommendations", "Destinations matched to your taste, budget and travel style."),
#         ("💸", "Smart Budget Planning", "See realistic cost estimates before you book anything."),
#         ("🌍", "Global Coverage", "Thousands of cities, hotels and airports at your fingertips."),
#     ]
#     cols = st.columns(3)
#     for c, (icon, title, desc) in zip(cols, features):
#         with c:
#             st.markdown(
#                 f"""
#                 <div class="tw-glass">
#                     <div class="tw-icon-circle">{icon}</div>
#                     <div style="font-weight:700; font-size:1.05rem; margin-bottom:.4rem;">{title}</div>
#                     <div class="tw-muted" style="font-size:.92rem; line-height:1.5;">{desc}</div>
#                 </div>
#                 """,
#                 unsafe_allow_html=True,
#             )
# 
# 
# def page_placeholder(title, icon, description):
#     st.markdown(f'<div class="tw-section-title">{icon} {title}</div>', unsafe_allow_html=True)
#     st.markdown(
#         f"""
#         <div class="tw-glass" style="text-align:center; padding:3.2rem 2rem;">
#             <div style="font-size:2.6rem; margin-bottom:1rem;">{icon}</div>
#             <div style="font-weight:700; font-size:1.3rem; margin-bottom:.6rem;">{title} is coming soon</div>
#             <div class="tw-muted">{description}</div>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
# 
# PAGE_CONTENT = {
#     "Plan Trip": ("🧳", "Build a day-by-day itinerary tailored to your preferences and travel dates."),
#     "AI Travel Assistant": ("🤖", "Chat with an AI assistant that answers your travel questions in real time."),
#     "Destination Explorer": ("📍", "Browse and filter destinations by climate, budget, and vibe."),
#     "Budget Planner": ("💰", "Estimate flights, hotels, and daily costs for your next trip."),
#     "Weather": ("🌦️", "Check destination forecasts before you pack."),
#     "Saved Trips": ("❤️", "All the destinations and plans you've bookmarked, in one place."),
#     "Settings": ("⚙️", "Manage your profile, preferences, and app settings."),
# }
# 
# 
# # ----------------------------------------------------------------------------
# # MAIN
# # ----------------------------------------------------------------------------
# def main():
#     inject_css()
# 
#     if "splash_done" not in st.session_state:
#         st.session_state.splash_done = False
#     if "page" not in st.session_state:
#         st.session_state.page = "Home"
# 
#     if not st.session_state.splash_done:
#         placeholder = st.empty()
#         with placeholder.container():
#             render_splash()
#         time.sleep(4.8)
#         st.session_state.splash_done = True
#         placeholder.empty()
#         st.rerun()
#         return
# 
#     render_sidebar()
# 
#     if st.session_state.page == "Home":
#         page_home()
#     else:
#         icon, desc = PAGE_CONTENT[st.session_state.page]
#         page_placeholder(st.session_state.page, icon, desc)
# 
# 
# if __name__ == "__main__":
#     main()